#+TITLE: 
#+OPTIONS: html-postamble:nil toc:nil num:nil author:nil timestamp:ni
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [utopia,letterpaper,10pt,microtype,paralist]
#+LATEX_HEADER: \usepackage[margin=.5in]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER_EXTRA: \setlength\parindent{0pt}
#+LATEX_HEADER_EXTRA: \pagestyle{empty}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css.css" />
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' />

* Resume of Evans Winner

#+BEGIN_CENTER
720.666.8803 \\
ego111@gmail.com \\
16359 West Tenth Avenue, Unit R4, Golden CO, 80401
#+END_CENTER

** Background and Skills

 - *System Administration:* 6 years IBM i on Power systems
   administration [SLFCU], 3 servers: AJS job scheduling (~300
   scheduled jobs); migrated old IBM jobs to AJS and automated weekend
   batch processing; project lead on successful simultaneous hardware (to
   Power 6) and OS level (to 7.0) upgrade on production system; BRMS
   config and maintenance; PTF and upgrades; backups; process
   monitoring and general system ops; 2nd-level user and dev support
   with iSupport.  Operations documentation and checklists
   maintenance.  Some light sysadmin on MS Windows (reboots,
   monitoring, job scheduling, Active Directory [SLT]).
 - *General Operations:* ~13 yrs IBM midrange operations; unsupervised
   off-shift work requiring independent problem-solving of hardware
   and software issues, understanding escalation procedures and
   critical / disaster recovery processes (5 years in a
   deadline-based, high-output production environment at a Fortune 500
   company [ADP]). Process and print queue management, network
   monitoring; report generation and distribution (~10,000--~100,000
   pages/day [ADP]); reel and cassette backups; printer maintenance
   (Oce 2040 / 750) [ADP]
 - *Web development:* Center for Infectious Disease and Immunity
   http://hsc.unm.edu/som/programs/cidi/ (2008); Albuquerque Civic
   Chorus (2012-2013, volunteer, full re-design, which has since been
   completely changed) http://abqchorus.org; idealstudios.com
   (1999-2001, now defunct).  Mainly cleaned up code and built new
   pages for CIDI and TVDC web pages (~25 pages, html, css,
   Javascript).
 - *Database:* Re-designed MS Access billing DB (re-built tables,
   improved UI and refactored VBA code [CIDI]. Implemented database
   for tracking tape library (~400 tapes) [SLFCU]. Manual (DFU) and
   SQL edits on live data [SLFCU].
 - *Phone-based support:* 1 year customer service-intensive grave
   shift phone support at a high-throughput commercial helpdesk
   supporting Thinnet-based POS systems [ParTech]: fixed operational
   errors; diagnosed hardware issues with touch-screens, printers,
   LAN, drives, etc.; setup of network routing and other configuration
   issues and software upgrades on ParTech's software.  Clarify
   support database client.  Closed 10-20 tickets per night.
 - *Other 1st level support:* Incidental email and in-person user
   support for POS systems (~60 retail sites [SLT]), handheld
   scanners, touch-screen kiosks, general Windows XP and Mac OS/X
   desktop and laptops. Misc. helpdesk and office assistance
   (installs, scanning, troubleshooting, system setup [TVDC]). Support
   for email clients and basic Unix CLI help in Solaris and other
   software on Macintosh; fixed problems with cabling (mostly
   MIDI-related) and application support for MOTU Digital Performer
   [CU].
 - *Progamming:* Wrote build tool for operational checklists
   [SLFCU]. Some programming ability in Common Lisp, Emacs Lisp,
   Windows batch, HTML, CSS, and to a lesser extent, CL (IBM Control
   Language), SQL, C#, awk, Unix / QSHELL scripting.  Github:
   https://github.com/EvansWinner
 - Perfect score on customer service portion of A+ exam.
 - 2001 perfect attendance award [ADP].

** History

 - *IS System Administrator I / System Administrator Senior.* Sandia
   Laboratory Federal Credit Union [SLFCU], Albuquerque NM. August
   2008---February 2015
 - *Webmaster / Database Support.* Center for Infectious Disease and
   Immunity [CIDI], University of New Mexico, Health Sciences Center,
   Department of Pathology, Albuquerque NM. January 2008---January 2009
   [part time]
 - *Desktop Support.* Tularemia Vaccine Development Contract [TVDC]
   laboratory University of New Mexico, Health Sciences Center,
   Department of Pathology, Albuquerque NM. January 2008---January 2009
   [part time]
 - *Computer Operator I / Computer Operator II.* Sur La Table, Inc
   [SLT], Seattle WA. February 2006---July 2007
 - *Computer Operator.* Automatic Data Processing [ADP], Bothell WA.
   July 2000---November 2005
 - *Associate Customer Engineer.* ParTech, Inc. (Through staffing
   agency Teksystems). Boulder CO. June 1999---June 2000.
 - *Computer Lab Monitor.* University of Colorado [CU], Boulder
   CO. January 1999---June 1999

** Education and Certifications
 - BA, English-Philosophy, /summa cum laude/, University of New
   Mexico, 2010
 - College and continuing ed courses in Pascal, C#, SQL, HTML5,
   digital audio and sound synthesis
 - CompTIA *A+* (6/26/00), *Linux+* (3/27/07), *I-Net+* (6/5/06)
   (CompTIA ID: COMP001005140520); Brainbench *MS-DOS 6* (expired)
