#+TITLE: 
#+OPTIONS: html-postamble:nil
#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER_EXTRA: \setlength\parindent{0pt}
#+OPTIONS: toc:nil num:nil author:nil timestamp:ni
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css.css" />
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' />


* Resume of Evans Winner

#+BEGIN_CENTER
951 Buena Vista Dr. SE, K-107 Albuquerque NM 87106 505.410.1546 \\
<[[mailto:ego111@gmail.com]]>
#+END_CENTER

** Overview

 - 12+ yrs IBM midrange sysop and sysadmin experience; much
   unsupervised off-shift work requiring independent problem-solving
   of hard- and software issues, understanding of escalation
   procedures and critical / disaster-recovery processes (5 yrs in a
   deadline-based, high-output production environment).  Phone, email
   and in-person support (1 year phone support for demanding
   commercial client. Perfect score on customer service portion of A+
   exam.
 - Web dev for idealstudios.com (1999-2001, now defunct); Albuquerque
   Civic Chorus (2012-2013, volunteer) http://abqchorus.org; Center
   for Infectious Disease and Immunity
   http://hsc.unm.edu/som/programs/cidi/.

** Experience

*IS System Administrator I / II* -- Sandia Labs Federal Credit Union,
Albuquerque NM 7/2008-Pres

 - IBM i on PowerSystems admin: AJS job scheduling, BRMS config and
   mainetencence; PTF and upgrades; backups; process monitoring and
   general system operations; second-level user and dev support.

*Webmaster* -- Center for Infectious Disease and Immunity, Albuquerque
NM 1/2008-1/2009
 
 - Web design/maintenence; helpdesk and general IT: CIDI and Tularemia
   Vaccine Development Contract web page; MS-Access billing db
   maint. and doc; misc. helpdesk (installs, scanning,
   troubleshooting, system setup) (CIDI and TVDC were officially
   separate employers)

*Computer Operator I / II* -- Sur La Table, Inc, Seattle WA
2/2006-7/2007

 - iSeries / Windows system operations: Process and print queue
   management, network monitoring; report generation and distribution.
   Support for POS systems, handheld scanners, touch-screen kiosks,
   general Windows XP and Mac OS/X desktop and laptops.

*Computer Operator* -- Automatic Data Processing, Bothell WA
   7/2000-11/2005

 - AS/400 / eServer midrange operations for payroll processing:
   Nightly batch jobs for financial transactions, tape and reel
   backups; misc. processes. Oce 2040 / 750 printer maint.; managed
   tape library and printer output.  2001 perfect attendance award.

*Associate Customer Engineer* -- ParTech, Inc., Boulder CO
6/1999-6/2000

 - Customer service-intensive grave shift phone support for
   Thinnet-based POS systems: Fixing operational errors; diagnosing
   hardware issues with touch-screens, printers, LAN, drives, etc;
   setup of network routing and other configuration issues and
   software upgrades on ParTech's software.  Used NT Workstation and
   Clarify support database client

*Computer Lab Monitor* -- University of Colorado, Boulder CO
1/1999-6/1999

 - Monitored university computer music lab. [Temp employee, not
   work-study]: Support for pine email client in UNIX and other
   Internet clients on Macintosh; fixing problems with cabling (mostly
   MIDI-related) and support for MOTU Digital Performer.

** Miscellaneous

 - Education: BA, English-Philosophy, University of New Mexico, 2010;
   UNM Continuing Ed courses in C#, SQL and HTML5.
 - Github: https://github.com/EvansWinner
 - Certifiations: CompTIA A+ 2000; CompTIA Linux+ 2007; CompTIA I-Net+
   2006; Brainbench MS-DOS 6

